
export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";

export const SET_CART_ITEMS = "SET_CART_ITEMS";
export const CLEAR_CART_ITEMS = "CLEAR_CART_ITEMS";


